version: 2.1

orbs:
  node: circleci/node@4.7.0
jobs:
  build_and_deploy_mainnet:
    resource_class: large
    docker:
      - image: 'cimg/node:18.0.0'
    steps:
      - checkout
      - run:
          name: download & unzip awscli v2
          command: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip
      - run:
          name: install awscli v2
          command: sudo ./aws/install
      # look for existing cache and restore if found
      - restore_cache:
          key: mtrscriber-deps-{{ checksum "package.json" }}
      - run:
          name: install npm dependencies
          command: npm install --force
      - save_cache:
          key: mtrscriber-deps-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: production build
          command: NODE_ENV=production npm run build
      - run:
          name: s3 sync
          command: aws s3 sync ./out/ s3://mtrscriber-meter-io/ --delete
      - run:
          name: invalidation
          command: aws cloudfront create-invalidation --distribution-id E2A196EABNII7M --paths "/*"
workflows:
  fresh_deploy:
    jobs:

      - build_and_deploy_mainnet:
          context: aws-2023
          filters:
            branches:
              only: meter
